baseURL = 'https://h-he-1-2.cyou/'
locale = 'zh-cn'
title = 'H-He-1-2'
theme = 'hugo-theme-stack'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
pluralizeListTitles = false

[pagination]
    pagerSize = 10

[permalinks]
    post = "/:section/:slug/"
    page = "/:slug/"
