[[main]]
    identifier = "home"
    name = "主页"
    url = "/"
    weight = 1

    [main.params]
        icon = "home"

[[main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2

    [main.params]
        icon = "categories"

[[main]]
    identifier = "physics"
    name = "物理"
    url = "/categories/物理/"
    weight = 3

    [main.params]
        icon = "infinity"

[[main]]
    identifier = "math"
    name = "数学"
    url = "/categories/数学/"
    weight = 4

    [main.params]
        icon = "hash"

[[main]]
    identifier = "stories"
    name = "故事"
    url = "/categories/故事/"
    weight = 5

    [main.params]
        icon = "messages"

[[main]]
    identifier = "chemistry"
    name = "化学"
    url = "/categories/化学/"
    weight = 6

    [main.params]
        icon = "tag"

[[main]]
    identifier = "questions"
    name = "问题"
    url = "/categories/问题/"
    weight = 7

    [main.params]
        icon = "search"

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/H-He-1-2"

    [social.params]
        icon = "brand-github"
