baseURL = 'https://H-He-1-2.github.io/'
locale = 'zh-cn'
title = 'H-He-1-2'
theme = 'relearn'

pluralizeListTitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 4

[params]
  math = true
  mathProvider = "katex"
  mermaid = true
  editURL = ""

[params.relearn]
  collapsibleMenu = true
  themeVariant = "auto"
  disableGeneratorVersion = true
